### ISSUE TITLE
.

### ISSUE THREAD

**Issue by eingress** [leoafarias/fvm#193]
.

**Comment by leoafarias** [comment]
@eingress I think there is some confusion on the instructions you actually have to pass your path into the command. <CACHE_PATH> is just a placeholder

**Comment by eingress** [comment]
Clearly I replaced the placeholder!!!

**Comment by leoafarias** [comment]
Mentioning that FVM_HOME works after saying you expected to be set to CACHE_PATH is confusing

**Comment by eingress** [comment]
You've literally assumed someone is stupid enough not to replace the placeholder; apparently you're also easily confused.

Way to go.

Please ignore this erroneous issue with your package.

**Comment by leoafarias** [comment]
You seem pleasant.

It seems like you are having a bad day, or is going through some personal issues so I will let this slide, but I do recommend you drop the attitude when trying to get people to help you on an open-source project.

I do get a lot of issues that are caused by simple user mistakes. There are a lot of new devs, and junior devs getting involved in Flutter, so these are more common than you think.

There is a reason why I did not close the issue, which was so I could get back to it later.

I will reopen it so I can actually keep track of it.

**Comment by eingress** [comment]
.

**Comment by leoafarias** [comment]
Just tested and could not replicate your issue. Let me know if there is any other information you would like to share.
