### ISSUE TITLE
[Feature Request] List all Flutter versions (unformatted)

### ISSUE THREAD

**Issue by abhaysood** [leoafarias/fvm#295]
It would be nice to have a way to list all Flutter versions in ascending order when running `fvm releases` without formatting and dates so that they can be used as input by other commands.

This can be used by CI systems to smartly install/cache certain versions of Flutter. Currently `fvm releases` gives a pretty output with release dates which is fine for human consumption but harder to parse for bots.

**Comment by leoafarias** [comment]
@abhaysood can you tell me your use case specifically for this?

**Comment by abhaysood** [comment]
CI on a particular project I'm working on uses Docker to configure the machines. I want my CI machines to always have a few versions of Flutter installed via FVM so that the pipelines do not need to spend time downloading it every time. To achieve this I was planning to install last 2-3 stable versions which most of the packages internally use.

Having a `fvm releases` command just prints the version numbers would be quite useful for this case as I won't need to hardcode the versions in my Dockerfile.

If you like the idea, more thought will be needed to figure out if we need to provide ways to filter the output by channel.

**Comment by leoafarias** [comment]
I think it's something that needs to be discussed. If you want to cache an SDK version on the CI, I would suggest to actually have the whole SDK installed and set up before running Flutter.

Right now FVM loads Flutter on-demand (default flutter behavior) It means it will download any platform dependencies as needed. If you always need iOS and Android, for example, it's better to have the full SDK cached locally. 

The initial FVM Flutter clone is around 80MB, the Full SDK with all deps is a couple of GB, so I wonder what would be the most efficient way to store this. Also, I wonder if a Docker image that has an array of versions might be the best way to accomplish this instead of an FVM feature.

**Comment by leoafarias** [comment]
@abhaysood will go ahead and close this issue. Take a look at https://github.com/leoafarias/flutter_flat_data if you want to discuss it further.
