### ISSUE TITLE
[BUG] bump fvm to support Dart 2.18.x

### ISSUE THREAD

**Issue by subzero911** [leoafarias/fvm#474]
![image](https://user-images.githubusercontent.com/12999702/192091240-4f3a30ce-1a93-4c20-97a7-3d8947c1627f.png)

fvm v2.4.1

**Comment by leoafarias** [comment]
@subzero911 does the issue happen when installing FVM through chocolatey also?

**Comment by subzero911** [comment]
> @subzero911 does the issue happen when installing FVM through chocolatey also?

Yes, I installed it through chocolatey

**Comment by subzero911** [comment]
@leoafarias could it be solved, if being installed not through choco, but through pub activate global?

Btw, it's dart `2.18.3` latest now

**Comment by JaffaKetchup** [comment]
I've run into this issue as well!

**Comment by subzero911** [comment]
Meanwhile, the next Dart version, 2.19.1, is out...

**Comment by leoafarias** [comment]
@subzero911 sorry for the delay on this again. I have to review a bit more in detail on why this issue is happening so often, I think maybe the constraints on FVM are incorrect, as it should not be happening with that much frequency

**Comment by leoafarias** [comment]
@subzero911 after doing a bit more research I don't think just upgrading the Dart version is a good solution for this, this might only help your case on Chocolatey since you want to have the latest version of Dart, but that is very restrictive for many other use cases including the `pub global actiavate`. 

I am doing a bit of research to understand how the chocolatey version is being built and deployed, as we use a package called `cli_pkg` for that.

**Comment by JaffaKetchup** [comment]
Hey @leoafarias, great work so far :) Is there any luck from your research?

**Comment by JaffaKetchup** [comment]
Hey, this ain't stale! Although I do fear FVM has been somewhat abandoned, which is a shame: I hope I'm wrong!

**Comment by JaffaKetchup** [comment]
@leoafarias With the release of Dart 3, this issue is now vastly more important! I would volunteer to help fix it, but unfortunately, I have no experience with Chocolatey internals.

**Comment by subzero911** [comment]
@leoafarias why it's such a bad idea to upgrade it manually?
I checked out other packages, and their authors just do it

<img width="639" alt="image" src="https://github.com/fluttertools/fvm/assets/12999702/4381678f-16a9-4c90-9737-6812534c2403">

**Comment by leoafarias** [comment]
It's not that we can't, but because fvm is a version manager it means that we need loser versions to guarantee compatibility with as many possible environments as possible. 

A package like mobx can be more aggressive, also I haven't had time to take a deeper look but I am still no clear on root of the problem since I don't see this happening with our internal use.

**Comment by JaffaKetchup** [comment]
Just to note, if using the standalone installation instructions, this issue doesn't occur. You can then just set the system PATH manually.

**Comment by subzero911** [comment]
Hi! That's great news!

**Comment by Chappie74** [comment]
Hey any updates on upgrading the dart version?
Currently unable to make use of dart 3.0.

![image](https://github.com/fluttertools/fvm/assets/21108487/71c2fed5-dd57-4092-b249-417e1c72df2d)

**Comment by leoafarias** [comment]
I suggest using the standalone binaries, brew or chocolatey. For the next version we will release an easier way to install the binaries also.

**Comment by Chappie74** [comment]
@leoafarias  this was with chocolately.  I have both dart and fvm installed using that. 

I am however able to work around it by pointing vs code to the dart sdk of the particular flutter version used via fvm.

**Comment by leoafarias** [comment]
@Chappie74 next week we will be releasing the next version which should hopefully address this issue

**Comment by leoafarias** [comment]
This is closed. The deploy actions for chocolatey and brew will now pin the compiled version to avoid this going forward.
