### ISSUE TITLE
Feature: fvm create

### ISSUE THREAD

**Issue by jascodes** [leoafarias/fvm#82]
I purpose `fvm create` be followed by selector from installed versions of flutter and based on selected one, it should proxy to `flutter create` of that version. After `flutter create`, `flutter use` or in future `flutter alias` also executed to hook up with fvm.

Thx

**Comment by leoafarias** [comment]
@jascodes this makes sense, but I am trying to be careful about not having flutter cli api that is being just proxied. I do think this is an interesting case especially for people using web, and desktop, since they are using unstable versions.

I think I will remove the guard to only allow to use the `fvm use` command on a flutter project, or at least allow for an override prompt. You will be able to do that using the following.
- mkdir <project>
- cd <project>
- `fvm use <version>`
- Prompt saying 'This is not a Flutter project. Are you sure you want to proceed?`
- This will setup fvm config in the project.
- Use `fvm flutter create`

Let me know if that works for your case.

**Comment by jascodes** [comment]
@leoafarias Your solution will works too and it makes sense on depending on flutter cli; plus its quick fix. Infact I tried that myself and stumbled upon by guard.

**Comment by leoafarias** [comment]
@all-contributors please add @jascodes for ideas
